services:
  app:
    container_name: blue-app
    build: app
    restart: unless-stopped
    depends_on:
      - db
    environment:
      NEXT_PUBLIC_VAPID_KEY: "${PUBLIC_VAPID_KEY}"
      DATABASE_URL: "postgres://blue:${POSTGRES_PASSWORD}@db/blue"
      HOSTNAME: "${HOSTNAME}"
  db:
    image: postgres:17
    environment:
      POSTGRES_USER: "blue"
      POSTGRES_PASSWORD: "${POSTGRES_PASSWORD}"
    volumes:
      - blue-data:/var/lib/postgresql/data
  server:
    build: server
    restart: unless-stopped
    depends_on:
      - db
    environment:
      HOSTNAME: "${HOSTNAME}"
      DATABASE_URL: "postgres://blue:${POSTGRES_PASSWORD}@db/blue"

volumes:
  blue-data:
