services:
  app:
    container_name: blue-app
    build: app
    restart: unless-stopped
    depends_on:
      - db
    environment:
      NEXT_PUBLIC_FIREBASE_API_KEY: "${FIREBASE_API_KEY}"
      NEXT_PUBLIC_FIREBASE_AUTH_DOMAIN: "${FIREBASE_AUTH_DOMAIN}"
      NEXT_PUBLIC_FIREBASE_PROJECT_ID: "${FIREBASE_PROJECT_ID}"
      NEXT_PUBLIC_FIREBASE_STORAGE_BUCKET: "${FIREBASE_STORAGE_BUCKET}"
      NEXT_PUBLIC_FIREBASE_MESSAGING_SENDER_ID: "${FIREBASE_MESSAGING_SENDER_ID}"
      NEXT_PUBLIC_FIREBASE_APP_ID: "${FIREBASE_APP_ID}"
      NEXT_PUBLIC_VAPID_KEY: "${PUBLIC_VAPID_KEY}"
      DATABASE_URL: "postgres://blue:${POSTGRES_PASSWORD}@db/blue"
      HOSTNAME: "${HOSTNAME}"
  db:
    image: postgres:17
    environment:
      POSTGRES_USER: "blue"
      POSTGRES_PASSWORD: "${POSTGRES_PASSWORD}"
    volumes:
      - blue-data:/var/lib/postgresql/data
  server:
    build: server
    restart: unless-stopped
    depends_on:
      - db
    environment:
      HOSTNAME: "${HOSTNAME}"
      DATABASE_URL: "postgres://blue:${POSTGRES_PASSWORD}@db/blue"

volumes:
  blue-data:
