services:
  app:
    container_name: blue-app
    build: app
    restart: unless-stopped
    depends_on:
      - db
    environment:
      NEXT_PUBLIC_HOSTNAME: "${PUBLIC_HOSTNAME}"
      NEXT_PUBLIC_SUBSCRIPTION_LIMIT: "${PUBLIC_SUBSCRIPTION_LIMIT}"
      NEXT_PUBLIC_VAPID_KEY: "${PUBLIC_VAPID_KEY}"
      DATABASE_URL: "postgres://blue:${POSTGRES_PASSWORD}@db/blue"
      EMAIL: "${EMAIL}"
  db:
    image: postgres:17
    environment:
      POSTGRES_USER: "blue"
      POSTGRES_PASSWORD: "${POSTGRES_PASSWORD}"
    volumes:
      - blue-data:/var/lib/postgresql/data
  server:
    build: server
    restart: unless-stopped
    depends_on:
      - db
    environment:
      DATABASE_URL: "postgres://blue:${POSTGRES_PASSWORD}@db/blue"

volumes:
  blue-data:
